# Generated by Django 4.1.7 on 2024-02-21 02:26

from django.db import migrations, models
import django_countries.fields


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_person_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='person',
            name='countries',
            field=django_countries.fields.CountryField(max_length=2, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='interest',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='langChosen',
            field=models.CharField(choices=[('En', 'English'), ('Sp', 'Spanish'), ('Ger', 'German'), ('Flip', 'Filipino'), ('Jap', 'Japanese')], default='English', max_length=4, null=True),
        ),
        migrations.AlterField(
            model_name='person',
            name='last_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
